{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "hpa-%s" (.Values.autoscaling.name | default (.Values.deployment.name | default .Release.Name)) }}
  namespace: {{ .Values.autoscaling.namespace | default .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.name | default .Release.Name }}
    {{- if .Values.autoscaling.labels }}
    {{- toYaml .Values.autoscaling.labels | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployment.name | default .Release.Name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
