{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default (.Values.deployment.name | default .Release.Name) }}
  labels:
    app: {{ .Values.deployment.name | default .Release.Name }}
    name: {{ .Values.namespace.name | default (.Values.deployment.name | default .Release.Name) }}
    {{- if .Values.deployment.labels }}
    {{- toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
{{- end }}
