apiVersion: v2
name: generic-deployment
description: A generic Helm chart for Kubernetes deployments with Istio VirtualService support
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - deployment
  - kubernetes
  - istio
  - virtualservice
maintainers:
  - name: DevOps Team
home: https://github.com/yourorg/helm-charts
sources:
  - https://github.com/yourorg/helm-charts

